apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-gateway
  template:
    metadata:
      labels:
        app: customer-gateway
    spec:
      containers:
      - name: customer-gateway
        image: chungjm0711/take-it-customer-gateway-svc-amd64:3.0
        ports:
        - containerPort: 8000
        env: 
        - name: spring.zipkin.base-url
          value: http://jaeger-collector.istio-system.svc.cluster.local:9411
---
apiVersion: v1
kind: Service
metadata:
  name: customer-gateway-service
spec:
  selector:
    app: customer-gateway
  ports:
  - port: 8000
    targetPort: 8000
