apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: customer-gateway
resources: 
- customer-gateway.yaml
images: 
- name: chungjm0711/take-it-customer-gateway-svc-amd64
  newTag: asdf
patchesStrategicMerge:
- customer-gateway.yaml
