apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noti
  template:
    metadata:
      labels:
        app: noti
    spec:
      containers:
      - name: notification
        image: chungjm0711/take-it-notification-svc-amd64:3.0
        env:
        - name: spring.datasource.url
          value: jdbc:mariadb://notification-db-service.default.svc.cluster.local:3306/notificationdb?characterEncoding=UTF-8
          #- name: eureka.client.service-url.defaultZone
          #value: http://discovery-service.default.svc.cluster.local:8761/eureka
        - name: kafka.host
          value: kafka-service.default.svc.cluster.local
        - name: spring.zipkin.base-url
          value: http://jaeger-collector.istio-system.svc.cluster.local:9411
        ports:
        - containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: noti
  ports:
  - port: 9100
    targetPort: 9100
